---

- name: check if prometheus already installed
  stat:
    path: "{{ prometheus_bin }}"
  register: check_prometheus_present

- name: check if prometheus configurations directory already installed
  stat:
    path: "{{ prometheus_dir_configuration }}"
  register: check_prometheus_configuration_present
       
- name: "[PROMETHEUS] - groupe prometheus"
  group:
    name: prometheus
    state: present

- name: "[PROMETHEUS] - user prometheus"
  user:
    name: prometheus
    group: prometheus
    shell: /usr/sbin/nologin
    system: true
    create_home: no

- name: "[PROMETHEUS] - create directory"
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: directory
  with_items:
    - "/etc/prometheus"
    - "/var/lib/prometheus"

- name: on recupère la version souhaite
  shell: "cat /etc/systemd/system/prometheus.service | grep Version | cut -d ' ' -f 4"
  when:  check_prometheus_present.stat.exists == true
  register: get_prometheus_version
  changed_when: false


- name: download and unzip prometheus
  unarchive:
    src: "{{ prometheus_source }}"
    dest: /tmp/
    remote_src: yes
  when: check_prometheus_present.stat.exists == false or not get_prometheus_version.stdout == prometheus_version or check_prometheus_configuration_present.stat.exists == false


- name: move the configuration files
  copy:
    src: "/tmp/{{ prometheus_name_unarchive }}/"
    dest: "{{ prometheus_dir_configuration }}"
    owner: prometheus
    group: prometheus
    mode: 0755
    directory_mode: yes
    remote_src: yes
  when: check_prometheus_configuration_present.stat.exists == false

- name: move the binary to the final destination
  copy:
    src: "/tmp/{{ prometheus_name_unarchive }}/prometheus"
    dest: "{{ prometheus_bin }}"
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes
  when: check_prometheus_present.stat.exists == false

- name: suppression du binaire dans /tmp
  file:
    path: /tmp/{{ prometheus_name_unarchive }}
    state: absent

- name: "open port 9090" 
  firewalld: 
    port: 9090/tcp
    permanent: yes 
    state: enabled 
  notify: reload firewalld 

- name: install service prometheus
  template:
    src: prometheus_service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0755

- name: config prometheus template
  template:
    src: prometheus.yml.j2
    dest: '{{ prometheus_dir_configuration }}/prometheus.yml'
    owner: prometheus
    group: prometheus
    mode: 0755
  notify: reload_daemon_and_restart_prometheus

- meta: flush_handlers

- name: service always started
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Disable SELinux
  selinux:
    state: disabled